# Generated by Django 2.1.2 on 2018-11-18 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('C_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('C_name', models.CharField(max_length=15)),
                ('C_credits', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('S_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('S_name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('S_email', models.EmailField(blank=True, default='farazuddin.m17@iiits.in', max_length=254)),
                ('S_password', models.CharField(max_length=50)),
                ('S_courses', models.ManyToManyField(to='students.Courses')),
            ],
        ),
    ]
